# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-PodSingle
version:      1.00
version_from: lib/Tk/PodSingle.pm
installdirs:  site
requires:
    Tk::Pod:                       0.9929

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
